"""add_attack_chain_models

Revision ID: 0276e2995876
Revises: 0c8cc65572b1
Create Date: 2025-11-14 18:49:05.143219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0276e2995876'
down_revision = '0c8cc65572b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_chain_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('key_timestamp_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=True),
    sa.Column('y_position', sa.Float(), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=100), nullable=True),
    sa.Column('mitre_technique', sa.String(length=100), nullable=True),
    sa.Column('mitre_subtechnique', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['attack_chains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_timestamp_id'], ['key_timestamps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_chain_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['attack_chain_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['attack_chain_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attack_chain_edges')
    op.drop_table('attack_chain_nodes')
    op.drop_table('attack_chains')
    # ### end Alembic commands ###
