"""Add IOC management model

Revision ID: 26625eae2213
Revises: 499e7aaf8036
Create Date: 2025-11-12 16:21:39.266745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26625eae2213'
down_revision = '499e7aaf8036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('enrichment_data', sa.JSON(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index('idx_ioc_project_type', ['project_id', 'ioc_type'], unique=False)
        batch_op.create_index('idx_ioc_status', ['status'], unique=False)
        batch_op.create_index('idx_ioc_value_type', ['value', 'ioc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_ioc_type'), ['ioc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_timeline_id'), ['timeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_value'))
        batch_op.drop_index(batch_op.f('ix_iocs_timeline_id'))
        batch_op.drop_index(batch_op.f('ix_iocs_project_id'))
        batch_op.drop_index(batch_op.f('ix_iocs_ioc_type'))
        batch_op.drop_index(batch_op.f('ix_iocs_entry_id'))
        batch_op.drop_index('idx_ioc_value_type')
        batch_op.drop_index('idx_ioc_status')
        batch_op.drop_index('idx_ioc_project_type')

    op.drop_table('iocs')
    # ### end Alembic commands ###
