"""Add report and report template models

Revision ID: 499e7aaf8036
Revises: 20251111183314
Create Date: 2025-11-12 12:10:38.428851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499e7aaf8036'
down_revision = '20251111183314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('generation_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activities_project_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('activities_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('comment_mentions', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint(batch_op.f('comment_mentions_mentioned_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_mentions_comment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['mentioned_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('is_edited',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint(batch_op.f('comments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comments_parent_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comments_entry_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'timeline_entries', ['entry_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('saved_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_queries_created_by'))
        batch_op.drop_index(batch_op.f('ix_saved_queries_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_saved_queries_is_shared'))
        batch_op.drop_index(batch_op.f('ix_saved_queries_team_id'))
        batch_op.drop_index(batch_op.f('ix_saved_queries_timeline_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_queries_timeline_id'), ['timeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_queries_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_queries_is_shared'), ['is_shared'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_queries_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_queries_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_entry_id_fkey'), 'timeline_entries', ['entry_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('comments_parent_id_fkey'), 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('comments_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('is_edited',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('comment_mentions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_mentions_comment_id_fkey'), 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('comment_mentions_mentioned_user_id_fkey'), 'users', ['mentioned_user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('activities_project_id_fkey'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    op.drop_table('reports')
    op.drop_table('report_templates')
    # ### end Alembic commands ###
