"""add_entry_links_table

Revision ID: 9f70440f5532
Revises: 0276e2995876
Create Date: 2025-11-14 19:10:29.643336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f70440f5532'
down_revision = '0276e2995876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_entry_id', sa.Integer(), nullable=False),
    sa.Column('to_entry_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_links')
    # ### end Alembic commands ###
