"""Add LLM analysis and MITRE ATT&CK models

Revision ID: fc63e3f40ac6
Revises: 9f70440f5532
Create Date: 2025-11-18 14:12:49.517184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc63e3f40ac6'
down_revision = '9f70440f5532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_tactics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tactic_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=True),
    sa.Column('parent_technique_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['mitre_techniques.id'], ),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_tactics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('total_examples', sa.Integer(), nullable=True),
    sa.Column('source_timelines', sa.JSON(), nullable=True),
    sa.Column('dataset_format', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('validated_examples', sa.Integer(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=50), nullable=True),
    sa.Column('mitre_tactic_id', sa.String(length=50), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('analyzed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mitre_tactic_id'], ['mitre_tactics.id'], ),
    sa.ForeignKeyConstraint(['mitre_technique_id'], ['mitre_techniques.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_analysis_results', schema=None) as batch_op:
        batch_op.create_index('idx_analysis_entry_id', ['entry_id'], unique=False)
        batch_op.create_index('idx_analysis_technique_id', ['mitre_technique_id'], unique=False)
        batch_op.create_index('idx_analysis_timeline_id', ['timeline_id'], unique=False)

    op.create_table('training_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('mitre_technique_id', sa.String(length=50), nullable=True),
    sa.Column('mitre_tactic_id', sa.String(length=50), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['training_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_id'], ['timeline_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mitre_tactic_id'], ['mitre_tactics.id'], ),
    sa.ForeignKeyConstraint(['mitre_technique_id'], ['mitre_techniques.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_examples', schema=None) as batch_op:
        batch_op.create_index('idx_training_dataset_id', ['dataset_id'], unique=False)
        batch_op.create_index('idx_training_validated', ['is_validated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_examples', schema=None) as batch_op:
        batch_op.drop_index('idx_training_validated')
        batch_op.drop_index('idx_training_dataset_id')

    op.drop_table('training_examples')
    with op.batch_alter_table('timeline_analysis_results', schema=None) as batch_op:
        batch_op.drop_index('idx_analysis_timeline_id')
        batch_op.drop_index('idx_analysis_technique_id')
        batch_op.drop_index('idx_analysis_entry_id')

    op.drop_table('timeline_analysis_results')
    op.drop_table('training_datasets')
    op.drop_table('mitre_techniques')
    op.drop_table('mitre_tactics')
    # ### end Alembic commands ###
